version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb_gastronomia
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: inventario_gastronomia
      MYSQL_USER: inventario_user
      MYSQL_PASSWORD: inv123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - red_inventario

  backend:
    build: .
    container_name: backend_inventario
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/inventario_gastronomia
      SPRING_DATASOURCE_USERNAME: inventario_user
      SPRING_DATASOURCE_PASSWORD: inv123
    networks:
      - red_inventario

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_gastronomia
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_USER: inventario_user
      PMA_PASSWORD: inv123
    ports:
      - "8081:80"
    networks:
      - red_inventario


volumes:
  db_data:

networks:
  red_inventario:
    driver: bridge
